refactor: improve code structure and readability

diff --git a/scripts/crud b/scripts/crud
--- a/scripts/crud
+++ b/scripts/crud
@@ -67,15 +67,40 @@ key_init() {
     done
 }
 
-write_headers() {
+# $1: Metadata file
+get_headers() {
+    awk -F ':' '/^key:/ {print $2}' "$1" | paste -s -d ":" -
+}
+
+# $1: Metadata File
+# $2: flag='noID'
+columns_menu() {
     local meta_file="$1"
-    local table_file="$2"
+    headers=$(get_headers "$meta_file")
+    num_cols=$(echo "$headers" | tr ':' '\n' | wc -l)
 
-    # Generate headers
-    header=$(awk -F ':' '/^key:/ {print $2}' "$meta_file" | paste -sd ":" -)
+    echo "Select a column:"
+    if [[ $2 != 'noID' ]]; then
+        echo "$headers" | tr ':' '\n' | nl -w 1 -s ") "
+    else
+        echo "$headers" | cut -d ':' -f2- | tr ':' '\n' | nl -w 1 -s ") "
+        ((num_cols--))
+    fi
 
-    # Write headers to the DB file
-    echo "$header" >"$table_file"
+    echo
+    clear_buffer
+    read -r -p "Enter column number: " col_choice
+
+    if ! is_int "$col_choice" || [[ $col_choice -lt 1 || $col_choice -gt $num_cols ]]; then
+        col_choice=''
+        col_name=''
+        echo "Invalid choice!"
+        return 1
+    fi
+
+    [[ $2 == 'noID' ]] && ((col_choice++))
+    col_name=$(echo "$headers" | cut -d ':' -f$((col_choice)))
+    return 0
 }
 
 validate_input() {
@@ -103,8 +128,7 @@ validate_input() {
     while :; do
         echo
         clear_buffer
-        read -r -p "$msg" value
-        value=$(trim_tolower "$value")
+        read -r -p "$msg" value && value=$(trim_tolower "$value")
         [[ "$value" == "N/A" ]] && value=""
 
         # Check PK constraint (must be unique and not null)
@@ -232,7 +256,7 @@ table_init() {
     cat "$1/.$2.temp" >>"$1/.$2"
     rm "$1/.$2.temp"
 
-    write_headers "$1/.$2" "$1/$2"
+    get_headers "$1/.$2" >"$table_file"
     echo -e "\nTable initialized succussfully"
     sleep 2
     crud_menu "$1/.$2" "$1/$2"
@@ -242,9 +266,10 @@ table_init() {
 # $2: Table Data File
 crud_menu() {
     rows_md=$(awk '/^rows/ {print NR}' "$1")
-    row_num=$(awk -v rows_md="$rows_md" 'NR==rows_md {print $NF}' "$1")
+    row_num=$(awk -F ":" -v rows_md="$rows_md" 'NR==rows_md {print $NF}' "$1")
     pk_md=$(awk '/^pk/ {print NR}' "$1")
     updated_at_md=$(awk '/^updated_at/ {print NR}' "$1")
+    col_name=''
 
     while true; do
         clear
@@ -273,7 +298,7 @@ crud_menu() {
             sleep 2
             ;;
         4)
-            find_record "$2"
+            find_record "$2" "$1"
             clear_buffer
             read -r -s -n 1 -p "Press any key to continue..."
             ;;
@@ -290,12 +315,6 @@ crud_menu() {
         esac
 
     done
-}
-
-# $1: Database Path
-# $2: Table to be created
-select_table() {
-    [[ -s "$1/$2" ]] && crud_menu "$1/.$2" "$1/$2" || table_init "$1" "$2"
 }
 
 insert_record() {
@@ -331,7 +350,8 @@ insert_record() {
     for attr in "${attributes[@]}"; do
         type="${field[$attr]}"
         constraints="${rules[$attr]}"
-        validate_input "$attr" "$type" "$constraints" "Enter $attr value (press enter for null value): "
+        [[ "$constraints" =~ notnull ]] && msg="Enter $attr value (cannot be empty): " || msg="Enter $attr value (press enter for empty value): "
+        validate_input "$attr" "$type" "$constraints" "$msg"
         new_row+="$reply:"
     done
 
@@ -355,12 +375,12 @@ delete_record() {
     echo "Welcome to the record deletion wizard!"
     echo "*****************************************"
 
-    find_record "$table_file"
+    find_record "$table_file" "$meta_file"
     [[ $? -ne 0 ]] && return 1
 
     echo "*****************************************"
     clear_buffer
-    read -r -n 1 -p "Are you sure you want to delete $matching_count record(s)? (y/n) " confirmation
+    read -r -n 1 -p "Are you sure you want to delete $matching_count record(s)? (y/Y) " confirmation
     [[ "$confirmation" != [Yy] ]] && {
         echo -e "\nDeletion cancelled."
         return 1
@@ -379,66 +399,29 @@ delete_record() {
 }
 
 # $1: Table Data File
-columns_menu() {
-    local table_file="$1"
-
-    # Read -r the header
-    clear_buffer
-    IFS=':' read -r -a headers <"$table_file"
-
-    echo "Select a column:"
-    for i in "${!headers[@]}"; do
-        echo "$((i + 1))- ${headers[i]}"
-    done
-    # echo "${headers[@]}" | tr ' ' '\n' | nl -w 1 -s ") "
-
-    clear_buffer
-    read -r -p "Enter column number: " choice
-
-    if [[ "$choice" =~ ^[0-9]+$ && "$choice" -ge 1 && "$choice" -le "${#headers[@]}" ]]; then
-        echo "${headers[$((choice - 1))]}" # Only print the selected column name
-    else
-        echo "Invalid choice!" >&2
-        return 1
-    fi
-}
-
-# $1: Table Data File
+# $2: Meta Data File
 find_record() {
     local table_file="$1"
+    local meta_file="$2"
 
     clear
     echo "Welcome to the Find wizard!"
     echo "*****************************************"
 
     clear_buffer
-    IFS=':' read -r -a headers <"$table_file"
-    echo "Select a column from the menu:"
-    for i in "${!headers[@]}"; do
-        echo "$((i + 1))) ${headers[i]}"
-    done
-    echo
-    clear_buffer
-    read -r -p "Enter column number: " choice
-    if [[ "$choice" =~ ^[0-9]+$ && "$choice" -ge 1 && "$choice" -le "${#headers[@]}" ]]; then
-        key="${headers[$((choice - 1))]}"
-    else
-        echo "Invalid choice!"
-        return 1
-    fi
+    columns_menu "$meta_file"
+    [[ $? -ne 0 ]] && return 1
 
+    key=$col_name
     key_index=$(awk -F ':' -v key="$key" 'NR==1 {for (i=1; i<=NF; i++) if ($i == key) print i}' "$table_file")
     [[ -z "$key_index" ]] && {
-        echo "Error: Column '$key' not found."
+        echo -e "\nError: Column '$key' not found."
         return 1
     }
 
     clear_buffer
-    read -r -p "Enter the value: " value
-    [[ -z "$value" ]] && {
-        echo -e "\nError: Value cannot be empty."
-        return 1
-    } || [[ "$value" =~ ^(N/A|n/a|NA|na)$ ]] && value="N/A"
+    read -r -p "Enter the value: " value && value=$(trim_tolower "$value")
+    [[ -z "$value" || "$value" =~ ^(n/a|na)$ ]] && value="N/A"
 
     # Make `matching_rec` and `matching_count` global
     escaped_value=$(echo "$value" | sed 's/[\/&]/\\&/g')
@@ -467,68 +450,47 @@ update_record() {
     echo "Welcome to the record/s updating wizard!"
     echo "*****************************************"
 
-    # Read -r column names
     clear_buffer
-    IFS=':' read -r -a headers <"$table_file"
-
-    echo "Select a column from the menu:"
-    local column_map=()
-    local display_index=1
-
-    # Display available columns while skipping "ID"
-    for i in "${!headers[@]}"; do
-        [ "${headers[i]}" == "ID" ] && continue
-        echo "$display_index) ${headers[i]}"
-        column_map[$display_index]="${headers[i]}"
-        ((display_index++))
-    done
-    echo
-    clear_buffer
-    read -r -p "Enter column number: " choice
-
-    if [[ ! "$choice" =~ ^[0-9]+$ || "$choice" -lt 1 || "$choice" -ge "$display_index" ]]; then
-        echo "Invalid choice!"
-        return 1
+    headers=$(get_headers "$meta_file")
+    if [[ "$headers" =~ ^ID ]]; then
+        columns_menu "$meta_file" 'noID'
+    else
+        columns_menu "$meta_file"
     fi
 
-    key="${column_map[$choice]}"
-
-    [[ "$key" == "ID" ]] && {
-        echo "Error: You cannot update the ID value."
-        return 1
-    }
+    [[ $? -eq 1 ]] && return 1
+    key=$col_name
 
     # Find column index
     local key_index=$(awk -F ':' -v key="$key" 'NR==1 {for (i=1; i<=NF; i++) if ($i == key) print i}' "$table_file")
     [[ -z "$key_index" ]] && {
-        echo "Error: Column '$key' not found."
+        echo -e "\nError: Column '$key' not found."
         return 1
     }
 
     clear_buffer
-    read -r -p "Enter the value to update: " old_value
-    [[ -z "$old_value" ]] && {
-        echo "Error: Value cannot be empty."
-        return 1
-    } || [[ "$old_value" =~ ^(N/A|n/a|NA|na)$ ]] && old_value="N/A"
+    read -r -p "Enter the value to update: " old_value && old_value=$(trim_tolower "$old_value")
+    [[ -z "$old_value" || "$old_value" =~ ^(n/a|na)$ ]] && old_value="N/A"
 
     local matching_rec=$(awk -F ':' -v idx="$key_index" -v val="$old_value" 'NR>1 && $idx == val' "$table_file")
 
     local matching_count=$([[ -n "$matching_rec" ]] && echo "$matching_rec" | wc -l || echo 0)
     [[ "$matching_count" -eq 0 ]] && {
-        echo "Error: No matching records found."
+        echo -e "\nError: No matching records found."
         return 1
     }
 
     local field_type=$(awk -F ":" -v key="$key" '$2 == key {print $3}' "$meta_file")
     local field_constraints=$(awk -F ":" -v key="$key" '$2 == key {print $4}' "$meta_file")
 
-    validate_input "$key" "$field_type" "$field_constraints" "Enter the new value (press enter for null value): "
+    [[ $constraints =~ notnull ]] && msg="Enter $attr value (cannot be empty): " || msg="Enter $attr value (press enter for empty value): "
+
+    validate_input "$key" "$field_type" "$field_constraints" "$msg"
     [[ $? -eq 0 ]] &&
         new_value="$reply"
 
     clear_buffer
-    read -r -n 1 -p "Are you sure you want to update $matching_count record(s)? (y/n) " confirmation
+    read -r -n 1 -p "Are you sure you want to update $matching_count record(s)? (y/Y) " confirmation
     [[ "$confirmation" != [Yy] ]] && {
         echo -e "\nUpdating cancelled."
         return 1
@@ -556,4 +518,10 @@ show_all_records() {
     clear
     [[ $(wc -l <"$table_file") -gt 1 ]] && column -t -s ':' "$table_file" && return 0
     echo "No records found." && return 1
+}
+
+# $1: Database Path
+# $2: Table to be created
+select_table() {
+    [[ -s "$1/$2" ]] && crud_menu "$1/.$2" "$1/$2" || table_init "$1" "$2"
 }
