Refactor: replaced if-else with logical operators
Simplified the code by replacing several if-else statements with logical operators.
This refactor reduces the lines of code and improves readability while keeping the same functionality.

diff --git a/scripts/db_table b/scripts/db_table
--- a/scripts/db_table
+++ b/scripts/db_table
@@ -8,14 +8,11 @@
 # $1: Database
 # codes: {0: empty, 1: not empty}
 is_empty() {
-	for item in "$1"/*
-	do
-		if [[ -s "$item" ]]
-		then
-			return 1
-		fi
-	done
-	return 0
+    for item in "$1"/*
+    do
+        [[ -s "$item" ]] && return 1
+    done
+    return 0
 }
 
 ########################################################################################
@@ -27,94 +24,46 @@ is_empty() {
 # $2: Database or Table to be created
 # $3: 'db': Database, 'table': Table
 create() {
-	if [[ -z $2 ]]
-	then
-		echo "Name cannot be whitespace"
-		return 1
-	elif [[ -e "$1"/"$2" ]]
-	then
-		echo "'$2' already exists."
-		return 1
-	fi
-
-	if [[ $3 == 'db' ]]
-	then
-		mkdir "$1"/"$2"
-	elif [[ $3 == 'table' ]]
-	then
-		touch "$1"/"$2"
-	fi
-	
-	echo "'$2' created successfully."
-	return 0
+    [[ -z $2 ]] && { echo "Name cannot be whitespace"; return 1; }
+    [[ -e "$1/$2" ]] && { echo "'$2' already exists."; return 1; }
+    
+    ([[ $3 == 'db' ]] && mkdir "$1/$2") || ([[ $3 == 'table' ]] && touch "$1/$2")
+    echo "'$2' created successfully."
+    return 0
 }
 
 # $1: parent directory
 # $2: Database or Table to be created
 # $3: 'db': Database, 'table': Table
 delete() {
-	del='y'
-	
-    if [[ -z $2 ]]
-	then
-		echo "Name cannot be whitespace"
-		return 1
-    elif [[ ! -e "$1"/"$2" ]]
+    del='y'
+    [[ -z $2 ]] && { echo "Name cannot be whitespace"; return 1; }
+    [[ ! -e "$1/$2" ]] && { echo "'$2' does not exist."; return 1; }
+    
+    if { [[ $3 == "db" ]] && ! is_empty "$1/$2"; } || { [[ $3 == "table" ]] && [[ -s "$1/$2" ]] }
     then
-        echo "'$name' does not exist."
-        return 1
-    fi
-
-    if [[ $3 == "db" ]]
-    then
-        if ! is_empty "$1"/"$2"
-        then
-            echo "The Database is not empty, are you sure you want to delete it?"
-            read -n 1 -p"press [y/Y] to confirm delete and any other key to cancel: " del
-            echo
-        fi
-    elif [[ $3 == "table" ]]
-    then
-        if [[ -s "$1"/"$2" ]]
-        then
-            echo "The Table is not empty, are you sure you want to delete it?"
-            read -n 1 -p"press [y/Y] to confirm delete and any other key to cancel: " del
-            echo
-        fi
-    else
-        echo "Invalid Type."
-        return 1
+        echo "'$2' is not empty, are you sure you want to delete it?"
+        read -n 1 -p "press [y/Y] to confirm delete and any other key to cancel: " del
+        echo
     fi
     
-    if [[ $del == [yY] ]]
-    then
-		rm -r "$1"/"$2"
-		echo "'$2' is deleted successfully."
-		return 0
-	else
-		echo "delete canceled"
-		return 1
-	fi
+    [[ $del != [yY] ]] && { echo "delete canceled"; return 1; }
+    
+    rm -r "$1/$2"
+    echo "'$2' is deleted successfully."
+    return 0
 }
-
 
 # $1: parent directory
 # $2: old name
 rename(){
-	read -p "Please enter the new name: " new_name
-	if [[ -z new_name ]]
-	then
-		echo "Invalid Name"
-		return 1
-	elif [[ -e "$1"/"$new_name" ]]
-	then
-		echo "$new_name already exists"
-		return 1
-	fi
-	
-	mv "$1/$2" "$1/$new_name"
-	echo "'$2' is renamed successfully to '$new_name'"
-	return 0
+    read -p "Please enter the new name: " new_name
+    [[ -z $new_name ]] && { echo "Name cannot be whitespace"; return 1; }
+    [[ -e "$1/$new_name" ]] && { echo "'$new_name' already exists"; return 1; }
+    
+    mv "$1/$2" "$1/$new_name"
+    echo "'$2' is renamed successfully to '$new_name'"
+    return 0
 }
 
 
diff --git a/scripts/menu b/scripts/menu
--- a/scripts/menu
+++ b/scripts/menu
@@ -7,126 +7,103 @@ source ./db_table
 ########################################################################################
 
 db_menu() {
-	while true
-	do
-		clear
-		echo "Welcome to our DBMS, select what you want to do:"
-		echo "1) Create Database."
-		echo "2) Select Database."
-		echo "3) Rename Database."
-		echo "4) Delete Database."
-		echo "5) Exit BDMS."
-
-		read -n 1 option
-		clear
-	
-		case $option in
-		1)
-			read -p "Please enter the name of the Database you want to create: " db_name
-			create "$dbs_path" "$db_name" "db"
-			sleep 2
-			;;
-		2)
-			read -p "Please enter the name of the Database you want to select: " db_name
-			
-			if [[ -e "$dbs_path/$db_name" ]]
-			then
-				table_menu "$db_name"
-			else
-				echo "'$db_name' does not exist."
-				sleep 2
-			fi
-			;;
-		3)
-			read -p "Please enter the name of the Database you want to rename: " db_name
-			
-			if [[ -e "$dbs_path/$db_name" ]]
-			then
-				rename "$dbs_path" "$db_name"
-			else
-				echo "'$db_name' does not exist."
-			fi
-			sleep 2
-			;;
-		4)
-			read -p "Please enter the name of the Database you want to delete: " db_name
-			delete "$dbs_path" "$db_name" "db"
-			sleep 2
-			;;
-		5)
-			echo Goodbye!
-			sleep 2
-			break
-			;;
-		*)
-            echo "Invalid option. Please try again."
-            sleep 2
+    while true
+    do
+        clear
+        echo "Welcome to our DBMS, select what you want to do:"
+        echo "1) Create Database."
+        echo "2) Select Database."
+        echo "3) Rename Database."
+        echo "4) Delete Database."
+        echo "5) Exit BDMS."
+        
+        read -n 1 option
+        clear
+        
+        case $option in
+            1)
+                read -p "Please enter the name of the Database you want to create: " db_name
+                create "$dbs_path" "$db_name" "db"
+                sleep 2
             ;;
-		esac
-	done
+            2)
+                read -p "Please enter the name of the Database you want to select: " db_name
+                [[ -z $db_name ]] && { echo "Name cannot be whitespace"; sleep 2; continue;}
+                ([[ ! -e "$dbs_path/$db_name" ]] && { echo "'$db_name' does not exist."; sleep 2; }) || table_menu "$db_name"
+            ;;
+            3)
+                read -p "Please enter the name of the Database you want to rename: " db_name
+                [[ -z $db_name ]] && { echo "Name cannot be whitespace"; sleep 2; continue;}
+                ([[ ! -e "$dbs_path/$db_name" ]] && echo "'$db_name' does not exist." ) || rename "$dbs_path" "$db_name"
+                sleep 2
+            ;;
+            4)
+                read -p "Please enter the name of the Database you want to delete: " db_name
+                delete "$dbs_path" "$db_name" "db"
+                sleep 2
+            ;;
+            5)
+                echo Goodbye!
+                sleep 2
+                break
+            ;;
+            *)
+                echo "Invalid option. Please try again."
+                sleep 2
+            ;;
+        esac
+    done
 }
 
 table_menu(){
-	db_path="$dbs_path/$1"
-	
-	while true
-	do
-		clear
-		echo "Select what you want to do in Database '"$1"':"
-		echo "1) Create Table."
-		echo "2) Select Table."
-		echo "3) Rename Table."
-		echo "4) Delete Table."
-		echo "5) Return to Main Menu."
-
-		read -n 1 option
-		clear
-
-		case $option in
-		1)
-			# metadata?
-			read -p "Please enter the name of the Table you want to create: " table_name
-			create "$db_path" "$table_name" "table"
-			sleep 2
-			;;
-		2)
-			read -p "Please enter the name of the Table you want to select: " table_name
-			
-			if [[ -e "$db_path/$table_name" ]]
-			then
-				# what to do here?
-				echo "$table_name selected"
-				sleep 2
-			else
-				echo "'$table_name' does not exist."
-				sleep 2
-			fi
-			;;
-		3)
-			read -p "Please enter the name of the Table you want to rename: " table_name
-			
-			if [[ -e "$db_path/$table_name" ]]
-			then
-				rename "$db_path" "$table_name"
-			else
-				echo "'$table_name' does not exist."
-			fi
-			sleep 2
-			;;
-		4)
-			read -p "Please enter the name of the Table you want to delete: " table_name
-			delete "$db_path" "$table_name" "table"
-			sleep 2
-			;;
-		5)
-			break
-			;;
-		*)
-            echo "Invalid option. Please try again."
-            sleep 2
+    db_path="$dbs_path/$1"
+    while true
+    do
+        clear
+        echo "Select what you want to do in Database '"$1"':"
+        echo "1) Create Table."
+        echo "2) Select Table."
+        echo "3) Rename Table."
+        echo "4) Delete Table."
+        echo "5) Return to Main Menu."
+        
+        read -n 1 option
+        clear
+        
+        case $option in
+            1)
+                # metadata?
+                read -p "Please enter the name of the Table you want to create: " table_name
+                create "$db_path" "$table_name" "table"
+                sleep 2
             ;;
-		esac
-	done
+            2)
+                # what to do here?
+                read -p "Please enter the name of the Table you want to select: " table_name
+                [[ -z $table_name ]] && { echo "Name cannot be whitespace"; sleep 2; continue;}
+                ([[ ! -e "$db_path/$table_name" ]] && echo "'$table_name' does not exist." ) || echo "$table_name selected"
+                sleep 2
+            ;;
+            3)
+                read -p "Please enter the name of the Table you want to rename: " table_name
+                [[ -z $table_name ]] && { echo "Name cannot be whitespace"; sleep 2; continue;}
+                ([[ ! -e "$db_path/$table_name" ]] && echo "'$table_name' does not exist." ) || rename "$db_path" "$table_name"
+                sleep 2
+            ;;
+            4)
+                read -p "Please enter the name of the Table you want to delete: " table_name
+                delete "$db_path" "$table_name" "table"
+                sleep 2
+            ;;
+            5)
+                break
+            ;;
+            *)
+                echo "Invalid option. Please try again."
+                sleep 2
+            ;;
+        esac
+    done
 }
 
 
