feat: Enhance database management with metadata
- Introduced metadata handling with hidden files named after each database or table.
- Fixed errors caused by spaces in bash code, improving script stability.
- Added new functionality to view databases and tables.
- Improved code organization by correcting import paths.
- Made the parent directory containing all databases hidden by renaming it with a dot prefix for privacy.
- Add .gitignore to ignore '.DBs' directory

diff --git a/scripts/menu b/scripts/menu
--- a/scripts/menu
+++ b/scripts/menu
@@ -2,7 +2,7 @@
 
 # imports:
 ##########
-source ./db_table
+source ./scripts/db_table
 
 ########################################################################################
 
@@ -15,7 +15,8 @@ db_menu() {
         echo "2) Select Database."
         echo "3) Rename Database."
         echo "4) Delete Database."
-        echo "5) Exit BDMS."
+        echo "5) View Databases."
+        echo "6) Exit BDMS."
         
         read -n 1 option
         clear
@@ -28,12 +29,12 @@ db_menu() {
             ;;
             2)
                 read -p "Please enter the name of the Database you want to select: " db_name
-                [[ -z $db_name ]] && { echo "Name cannot be whitespace"; sleep 2; continue;}
+                [[ -z "$db_name" ]] && { echo "Name cannot be whitespace"; sleep 2; continue; }
                 ([[ ! -e "$dbs_path/$db_name" ]] && { echo "'$db_name' does not exist."; sleep 2; }) || table_menu "$db_name"
             ;;
             3)
                 read -p "Please enter the name of the Database you want to rename: " db_name
-                [[ -z $db_name ]] && { echo "Name cannot be whitespace"; sleep 2; continue;}
+                [[ -z "$db_name" ]] && { echo "Name cannot be whitespace"; sleep 2; continue; }
                 ([[ ! -e "$dbs_path/$db_name" ]] && echo "'$db_name' does not exist." ) || rename "$dbs_path" "$db_name"
                 sleep 2
             ;;
@@ -43,6 +44,12 @@ db_menu() {
                 sleep 2
             ;;
             5)
+                content=$(ls "$dbs_path")
+                ([[ -z "$content" ]] && echo "No Databases exist") || { echo "Databases:"; echo; echo "$content"; }
+                echo
+                read -n 1 -p "press any key to continue..."
+            ;;
+            6)
                 echo Goodbye!
                 sleep 2
                 break
@@ -65,7 +72,8 @@ table_menu(){
         echo "2) Select Table."
         echo "3) Rename Table."
         echo "4) Delete Table."
-        echo "5) Return to Main Menu."
+        echo "5) View Tables."
+        echo "6) Return to Main Menu."
         
         read -n 1 option
         clear
@@ -80,13 +88,13 @@ table_menu(){
             2)
                 # what to do here?
                 read -p "Please enter the name of the Table you want to select: " table_name
-                [[ -z $table_name ]] && { echo "Name cannot be whitespace"; sleep 2; continue;}
+                [[ -z "$table_name" ]] && { echo "Name cannot be whitespace"; sleep 2; continue; }
                 ([[ ! -e "$db_path/$table_name" ]] && echo "'$table_name' does not exist." ) || echo "$table_name selected"
                 sleep 2
             ;;
             3)
                 read -p "Please enter the name of the Table you want to rename: " table_name
-                [[ -z $table_name ]] && { echo "Name cannot be whitespace"; sleep 2; continue;}
+                [[ -z "$table_name" ]] && { echo "Name cannot be whitespace"; sleep 2; continue; }
                 ([[ ! -e "$db_path/$table_name" ]] && echo "'$table_name' does not exist." ) || rename "$db_path" "$table_name"
                 sleep 2
             ;;
@@ -96,6 +104,12 @@ table_menu(){
                 sleep 2
             ;;
             5)
+                content=$(ls "$db_path")
+                ([[ -z "$content" ]] && echo "No Tables in '$1' exist") || { echo "Tables in '$1':"; echo; echo "$content"; }
+                echo
+                read -n 1 -p "press any key to continue..."
+            ;;
+            6)
                 break
             ;;
             *)
